### ISSUE TITLE
speedhack not working

### ISSUE THREAD

**Issue by ghost** [Very-Tall-Midget/OmegaBot2#1]
pretty self explanatory, speedhack doesn't work in obot but i can still slow the gameplay down with mega hack's speedhack in classic mode

**Comment by TEFOwen** [comment]
Do you have smoothfix and vsync off?

**Comment by ghost** [comment]
yeah I do

**Comment by TEFOwen** [comment]
Do you have mhv7 fps bypass off and any other fps/speedhack or smoothfix options off?

**Comment by ghost** [comment]
Yep I have them all turned off

**Comment by TEFOwen** [comment]
can you upload a screen shot of your mh settings

**Comment by ghost** [comment]
Wait, I unloaded a DLL and the speedhack works now, sorry
